set nocompatible
filetype plugin indent on
syntax on

set nowrap number mouse=a clipboard=unnamed
set hlsearch tabstop=2 shiftwidth=2 expandtab
set cursorline colorcolumn=100

nmap <Leader><Space> :noh<Enter>

autocmd BufNewFile,BufRead Podfile,*.podspec set filetype=ruby
