map <C-n> :NERDTreeToggle<CR>
map <C-j> :NERDTreeFind<CR>
map <leader>gb :Gblame<CR>

nmap <Leader><Space> :noh<Enter>

colorscheme smyck

set wrap!
set number

set mouse=a
set clipboard=unnamed
set hlsearch

filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set cursorline
set colorcolumn=100

execute pathogen#infect()

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

:syntax on

Plugin 'VundleVim/Vundle.vim'
Plugin 'ervandew/supertab'
Plugin 'tpope/vim-rails.git'
Plugin 'airblade/vim-gitgutter'
Plugin 'elzr/vim-json'
Plugin 'leafgarland/typescript-vim'
Plugin 'craigemery/vim-autotag'
Plugin 'scrooloose/nerdcommenter'
Plugin 'tpope/vim-fugitive'
Plugin 'udalov/kotlin-vim'
Plugin 'mileszs/ack.vim'
Plugin 'keith/swift.vim'
Plugin 'dense-analysis/ale'

call vundle#end()
filetype plugin indent on

autocmd BufNewFile,BufRead Podfile,*.podspec set filetype=ruby