##############################################################
# load Square specific bash_profile
##############################################################
source ~/Development/config_files/square/bash_profile
##############################################################


###########################################
# Feel free to make your own changes below.
###########################################


# vim: filetype=sh

source ~/dotfiles/files/ms_bash_profile
