source ~/.bashrc
PATH=$PATH:~/bin
export PATH=/usr/local/bin:$PATH:/usr/local/sbin
source ~/.git-prompt.sh
export GIT_MERGE_AUTOEDIT=no
export EDITOR='vim'
export PORT='3000'

alias code='cd ~/Documents/code'

export ELASTICSEARCH_HOST='localhost:9200'
export PARALLEL_TESTS=4

BLACK="\[\033[0;30m\]"
RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
YELLOW="\[\033[0;33m\]"
PINK="\[\033[0;35m\]"
BLUE="\[\033[0;36m\]"
WHITE="\[\033[1;37m\]"
OFF="\[\033[0m\]"

export PS1="\n$YELLOW\$(~/.rvm/bin/rvm-prompt v) $BLUE\W $RED\$(__git_ps1 "%s")$OFF$GREEN \n ➲ $OFF "
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

alias redis='redis-server /usr/local/etc/redis.conf'
alias resque="QUEUE=* rake resque:work"
alias rake="bundle exec rake"
alias ship='git push origin master && git push heroku master'

## Rails Related
alias migrate='rake db:migrate db:test:prepare'
alias rs='bundle exec rails server'
alias rc='bundle exec rails c'
alias rg='bundle exec rails g'
alias rd='bundle exec rails dbconsole'
alias rr='rake routes'
alias cl='rake log:clear'

## Git Related
alias gcm='git commit -m'
alias gs='git status'
alias gl='git log'
alias ga='git add .'
alias gui='git gui'
alias gb='git branch'
alias gc='git checkout'
alias gpc='git push origin `cb`'
alias guc='git pull origin `cb`'
alias gphm='git push heroku master'
alias gr='git remote -v'
alias vim='mvim -v'

alias fs='foreman start'
alias cb='(__git_ps1 "%s") | pbcopy | (__git_ps1 "%s")'

alias reset_audio='sudo killall coreaudiod'

function rv() {
  REPO_URL=`gr | ack "((\w)*\/([\w-])*)" -o -1`
  open https://github.com/$REPO_URL/compare/`cb`
}

function pse() {
  ps -e | ack $1
}

function reload() {
  CURRENT_DIR=`pwd`
  cd ~/dotfiles
  ga
  ga -u
  gcm 'updating bash'
  git pull origin master
  git push origin master
  bundle install
  bundle exec rake
  source ~/.bash_profile
  cd $CURRENT_DIR
}

function fu_whitespace() {
  find . -name "*.rb" -print0 | xargs -0 perl -pi -e 's/ +$//'
}

function sportsball_update_scraper() {
  code
  cd sportsball
  cd sportsball-rails
  rm Gemfile.lock
  bundle
  ga
  gcm 'updating espn scraper'
  ship

  code
  cd sportsball
  cd sportsball-workers
  rm Gemfile.lock
  bundle
  ga
  gcm 'updating espn scraper'
  git push heroku master
}

unset LANG

# place in ~/.bash_profile as the very last line
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
