map <C-n> :NERDTreeToggle<CR>
map <C-j> :NERDTreeFind<CR>
map <leader>gb :Gblame<CR>

nmap <Leader><Space> :noh<Enter>

syntax on
colorscheme smyck

set wrap!
set number

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set mouse=a
set clipboard=unnamed
set hlsearch

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set cursorline
set colorcolumn=100

execute pathogen#infect()

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'ervandew/supertab'
Plugin 'tpope/vim-rails.git'
Plugin 'airblade/vim-gitgutter'
Plugin 'elzr/vim-json'
Plugin 'Valloric/YouCompleteMe'
Plugin 'leafgarland/typescript-vim'
Plugin 'craigemery/vim-autotag'
Plugin 'scrooloose/nerdcommenter'
Plugin 'tpope/vim-fugitive'
Plugin 'udalov/kotlin-vim'

call vundle#end()
filetype plugin indent on

autocmd BufNewFile,BufRead Podfile,*.podspec set filetype=ruby
