map <C-n> :NERDTreeToggle<CR>
map <C-j> :NERDTreeFind<CR>

nmap <Leader><Space> :noh<Enter>

syntax on
colorscheme smyck

set wrap!
set number

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set mouse=a
set clipboard=unnamed
set hlsearch

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

execute pathogen#infect()
